### PR TITLE
fix: vite compatibility issue

### LINKED ISSUE #874: Bug: Incompatibility issue with vite
### Describe the bug

In vite, installed in a project with vue 2, the environment variables import.meta.env are used. As a result, after installing the module an error occurs in the file node_modules/@coinbase/wallet-sdk/dist/CoinbaseWalletSDK.js - "process is not defined", because by default the module uses variables of type process.env.

### Steps

1. In an existing project with vue 2 and @coinbase/wallet-sdk installed, install vite and remove vue-cli dependencies
2. Install vite compatibility plugin with vue 2: npm i @vitejs/plugin-vue2
3. adjust the vite.config.js file and replace all process.env with import.meta.env
3. Run the project: npm run dev

### Expected behavior

I would like to be able to override the process.env assignment within the plugin to the one supported in vite - import.meta.env. Ideally, if it were possible to configure this in the vite.config.js file

### Version

"@coinbase/wallet-sdk": "^3.5.2"

### Additional info

_No response_

### Desktop

_No response_

### Smartphone

_No response_

### PR DESCRIPTION
**Pull request by VladimirMikulic**
### _Summary_

Resolves #874

TSC is used to compile release version of the library, which can't polyfill/substitute process.env object like Webpack.
This caused compilation error since process.env doesn't exist in the browser (unless substituted).

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
@cb-jake @bangtoven I'd appreciate a review when you're available. Thanks :)

File: packages/wallet-sdk/src/CoinbaseWalletSDK.ts [hunk 1]
```diff
@@ -13,11 +13,12 @@ import { MobileRelay } from './relay/MobileRelay';
...
 import { getFavicon, isMobileWeb } from './util';
+import { LIB_VERSION } from './version';
 
-const LINK_API_URL = process.env.LINK_API_URL || 'https://www.walletlink.org';
+const LINK_API_URL =
+  (typeof process !== 'undefined' && process.env?.LINK_API_URL) || 'https://www.walletlink.org';
 
-// eslint-disable-next-line @typescript-eslint/no-var-requires
-const SDK_VERSION = process.env.SDK_VERSION! || require('../package.json').version || 'unknown';
+const SDK_VERSION = (typeof process !== 'undefined' && process.env?.SDK_VERSION) || LIB_VERSION;
```
Comment (cb-jake) [inline packages/wallet-sdk/src/CoinbaseWalletSDK.ts:21]: We should just remove the process.env vars.

```suggestion
const SDK_VERSION = LIB_VERSION || require("./package.json").version; // will require a //@ts-expect-error or eslint disable.
```

File: packages/wallet-sdk/src/CoinbaseWalletSDK.ts [hunk 2]
```diff
@@ -13,11 +13,12 @@ import { MobileRelay } from './relay/MobileRelay';
 import { WalletLinkRelay } from './relay/WalletLinkRelay';
 import { WalletSDKRelayEventManager } from './relay/WalletSDKRelayEventManager';
 import { getFavicon, isMobileWeb } from './util';
+import { LIB_VERSION } from './version';
 
-const LINK_API_URL = process.env.LINK_API_URL || 'https://www.walletlink.org';
+const LINK_API_URL =
+  (typeof process !== 'undefined' && process.env?.LINK_API_URL) || 'https://www.walletlink.org';
```
Comment (cb-jake) [inline packages/wallet-sdk/src/CoinbaseWalletSDK.ts:19]: Lets make a constants file in the wallet-sdk package root and just define the `LINK_API_URL` var as a constant within that file and import that here.

**Review by cb-jake — CHANGES_REQUESTED** [review]
see inline comments

**Comment by cb-heimdall** [comment]
Review Error for cb-jake @ 2023-07-27 17:02:57 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

File: packages/wallet-sdk/src/CoinbaseWalletSDK.ts (hunk 1 above)
Comment (VladimirMikulic) [reply packages/wallet-sdk/src/CoinbaseWalletSDK.ts:21]: :+1:

File: packages/wallet-sdk/src/CoinbaseWalletSDK.ts (hunk 2 above)
Comment (VladimirMikulic) [reply packages/wallet-sdk/src/CoinbaseWalletSDK.ts:19]: :+1:

File: packages/wallet-sdk/src/CoinbaseWalletSDK.ts (hunk 1 above)
Comment (VladimirMikulic) [reply packages/wallet-sdk/src/CoinbaseWalletSDK.ts]: I replaced SDK_VERSION with LIB_VERSION since it's always defined in version.ts so require("./package.json") will never run.

**Comment by VladimirMikulic** [comment]
Thank you @cb-jake! Done.

File: packages/wallet-sdk/src/CoinbaseWalletSDK.ts [hunk 3]
```diff
@@ -51,7 +48,7 @@ export interface CoinbaseWalletSDKOptions {
 }
 
 export class CoinbaseWalletSDK {
-  public static VERSION = SDK_VERSION;
+  public static VERSION = LIB_VERSION;
```
Comment (cb-jake) [inline packages/wallet-sdk/src/CoinbaseWalletSDK.ts:51]: I think we should still import the package json as a fallback. `require('../package.json').version` This should happen outside of the class

Comment (VladimirMikulic) [reply packages/wallet-sdk/src/CoinbaseWalletSDK.ts:51]: @cb-jake I could import it, but it's unreachable code / it will never get referenced/used.
(LIB_VERSION is hard coded string in version.ts file which gets updated for each release, it's truthy value)

Comment (cb-jake) [reply packages/wallet-sdk/src/CoinbaseWalletSDK.ts:51]: Aww, I was thinking the version file only existed when a build happens. Nvmd. This looks good as is. Thanks!

**Comment by cb-jake** [comment]
Changes look good and this helps remove the need for the process polyfill. Once the build succeeds I'll get it merged

**Comment by VladimirMikulic** [comment]
Amazing! Thank you so much @cb-jake!

File: packages/wallet-sdk/src/CoinbaseWalletSDK.ts (hunk 3 above)
Comment (VladimirMikulic) [reply packages/wallet-sdk/src/CoinbaseWalletSDK.ts:51]: All good :+1:

**Review by cb-jake — APPROVED** [review]

**Comment by scotthconner** [comment]
This hasn't been released yet has it? Still ooks like 3.7.1 is the latest and that still has the issue.
